#Production Environment
prod:
  bind: 127.0.0.1
  port: 80
  mongo_uri: 'mongodb://username:password@hostname.example:27017/?retryWrites=true&w=majority&readPreference=nearest'

# Development Environment
dev:
  bind: 127.0.0.1
  port: 8030
  mongo_uri: 'mongodb+srv://username:password@hostname.example/?retryWrites=true&w=majority&readPreference=nearest'